---
- name: Install remote facts
  hosts: webserver
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:

    - name: Crear directorio remoto
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"

    - name: Instalar nuevos facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
