---
- name: Playbook template example
  hosts: all
  user: devops
  become: true
  vars:
    system_owner: clyde@example.com
  tasks:

    - name: Install template motd.j2
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644

