---
- name: Schedule at task
  hosts: webservers
  become: false
  tasks:

    - name: Ensure installed package at
      yum:
        name: at
        state: present
      become: true

    - name: Start and Enable service at
      service:
        name: atd
        enabled: true
        state: started
      become: true

    - name: Create date and time file
      at:
        command: "date > ~devops/my_at_date_time"
        count: 1
        units: minutes
        unique: yes
        state: present
